### ISSUE TITLE
How to remove the h3 title

### ISSUE THREAD

**Issue by laariiane** [RobinCK/vue-gallery#95]
Hello, I tried to remove the h3 title doing this 

template : 

    <gallery :images="images" :index="index" @close="index = null"  :options="galleryOptions"> </gallery>

vue : 

    data() {
            return {
                galleryOptions:{
                    titleElement: 'p',
                },
            }
        },

But it doesn't change anything, still a h3.

**Comment by RobinCK** [comment]
Hi @laariiane I do not see this option in the source https://github.com/RobinCK/vue-gallery/blob/master/src/component/gallery.vue#L104

**Comment by laariiane** [comment]
It's in BlueImp gallery options isn't it supposed to work like that ? 
https://github.com/RobinCK/vue-gallery#props
https://github.com/blueimp/Gallery#options

**Comment by RobinCK** [comment]
hmm ok

`// The tag name, Id, element or querySelector of the title element:`

I think that this option is needed by blueimp / Gallery in order for it to be able to find the title and changed it in DOM, but this does not mean that it will be rendered.

This option does not affect the vue-gallery itself, since h3 is hardcoded
https://github.com/RobinCK/vue-gallery/blob/master/src/component/gallery.vue#L8

if you need PR welcome :)
need add titleTag props

**Comment by laariiane** [comment]
Ah ok I understand, thank you. But I still need to remove it due to SEO request, or to be able to replace it with a neutral tag name. I'm not sure how PR works on Github sorry.
